josejr.
chary.
fanny.
estela.
paola.
josesr.
male(josejr).
female(chary).
female(fanny).
female(estela).
female(paola).
male(josesr).
parent(paola,josesr).
parent(paola,estela).
parent(fanny,josesr).
parent(fanny,estela).
parent(chary,josesr).
parent(chary,estela).
parent(josejr,josesr).
parent(josejr,estela).
mother(paola,estela).
mother(fanny,estela).
mother(josejr,estela).
mother(chary,estela).
father(paola,josersr).
father(fanny,josesr).
father(chary,josesr).
father(josejr,josesr).
sister(X,Y):-female(Y),mother(X,Z),mother(Y,Z),\+X=Y.
brother(X,Y):-male(Y),mother(X,Z),mother(Y,Z),\+X=Y.

